# Generated by Django 5.1.4 on 2025-01-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_the_mosque', models.CharField(max_length=500)),
                ('allah_helps_those', models.CharField(max_length=1000)),
                ('description_about', models.TextField()),
                ('our_vision', models.CharField(max_length=500)),
                ('description_our_vision', models.TextField()),
                ('our_mission', models.CharField(max_length=500)),
                ('description_our_mission', models.TextField()),
                ('raised', models.CharField(max_length=500)),
                ('raised_value', models.CharField(max_length=500)),
                ('description_raised', models.TextField()),
                ('charity_and_donation', models.CharField(max_length=500)),
                ('parent_education', models.CharField(max_length=500)),
                ('hadith_and_sunnah', models.CharField(max_length=500)),
                ('mosque_development', models.CharField(max_length=500)),
            ],
        ),
    ]
