# Generated by Django 5.1.4 on 2025-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=500)),
                ('activity_mosque_development', models.CharField(max_length=500)),
                ('description_activity_mosque_development', models.TextField()),
                ('activity_charity_donation', models.CharField(max_length=500)),
                ('description_activity_charity_donation', models.TextField()),
                ('activity_quran_learning', models.CharField(max_length=500)),
                ('description_activity_quran_learning', models.TextField()),
                ('activity_hadith_sunnah', models.CharField(max_length=500)),
                ('description_activity_hadith_sunnah', models.TextField()),
                ('activity_parent_education', models.CharField(max_length=500)),
                ('description_activity_parent_education', models.TextField()),
                ('activity_help_orphans', models.CharField(max_length=500)),
                ('description_activity_help_orphans', models.TextField()),
                ('activity_testimonial', models.CharField(max_length=500)),
                ('activity_title_testimonial', models.CharField(max_length=500)),
            ],
        ),
    ]
