# Generated by Django 5.1.4 on 2025-01-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0003_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.CharField(max_length=500)),
                ('description_title_event', models.TextField()),
                ('link_event', models.URLField(max_length=4500)),
                ('img_url_event', models.ImageField(blank=True, max_length=5500, null=True, upload_to='events_images/')),
                ('date_event', models.DateField()),
                ('time_event', models.TimeField()),
                ('day_event', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
            ],
        ),
    ]
