# Generated by Django 5.1.4 on 2025-01-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=100)),
                ('error_title', models.CharField(max_length=555)),
                ('error_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='link_event',
            field=models.URLField(blank=True, max_length=4500, null=True),
        ),
    ]
