# Generated by Django 5.1.4 on 2025-01-05 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0005_error404_alter_event_link_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_title', models.CharField(max_length=500)),
                ('description_sermon', models.TextField()),
                ('link_sermon', models.URLField(blank=True, max_length=4500, null=True)),
                ('img_url_sermon', models.ImageField(blank=True, max_length=5500, null=True, upload_to='sermons_images/')),
                ('date_sermon', models.DateField()),
                ('time_sermon', models.TimeField()),
                ('day_sermon', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('user_sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
