# Generated by Django 5.1.4 on 2025-01-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0006_sermon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=500)),
                ('description_blog', models.TextField()),
                ('link_blog', models.URLField(blank=True, max_length=4500, null=True)),
                ('img_url_blog', models.ImageField(blank=True, max_length=5500, null=True, upload_to='sermons_images/')),
                ('date_blog', models.DateField()),
                ('time_blog', models.TimeField()),
                ('day_blog', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('number_coments_blog', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Number Comments Blog')),
                ('user_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
