# Generated by Django 5.1.4 on 2025-01-05 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0007_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_full_name', models.CharField(max_length=500)),
                ('team_position', models.CharField(blank=True, max_length=500, null=True)),
                ('team_status', models.CharField(max_length=500)),
                ('team_life_situation', models.CharField(max_length=500)),
                ('team_description', models.TextField()),
                ('team_date_of_birth', models.DateField()),
                ('team_email', models.EmailField(max_length=254)),
                ('team_address', models.TextField()),
                ('team_phone_number', models.CharField(max_length=15)),
                ('team_link', models.URLField(blank=True, max_length=4500, null=True)),
                ('team_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='team_images/')),
                ('team_date_start', models.DateField()),
                ('team_time_start', models.TimeField()),
                ('team_day_start', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('team_social_links', models.JSONField(blank=True, null=True)),
                ('user_creator_team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
