# Generated by Django 5.1.4 on 2025-01-05 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0008_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('testimonial_position', models.CharField(blank=True, max_length=500, null=True)),
                ('testimonial_status', models.CharField(blank=True, max_length=500, null=True)),
                ('testimonial_description', models.TextField(blank=True, null=True)),
                ('testimonial_date_of_birth', models.DateField(blank=True, null=True)),
                ('testimonial_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('testimonial_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('testimonial_link', models.URLField(blank=True, max_length=4500, null=True)),
                ('testimonial_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='testimonial_images/')),
                ('testimonial_date', models.DateField(blank=True, null=True)),
                ('testimonial_time', models.TimeField(blank=True, null=True)),
                ('testimonial_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True)),
                ('testimonial_social_links', models.JSONField(blank=True, null=True)),
                ('user_creator_testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
