# Generated by Django 5.1.4 on 2025-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0010_sermon_file_sermon_alter_teammember_team_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_event',
            field=models.FileField(blank=True, max_length=5500, null=True, upload_to='sevents_files/'),
        ),
    ]
