# Generated by Django 5.1.4 on 2025-01-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0011_event_file_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file_event',
            field=models.FileField(blank=True, max_length=5500, null=True, upload_to='events_files/'),
        ),
    ]
