# Generated by Django 5.1.4 on 2025-01-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0013_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file_about',
            field=models.FileField(blank=True, max_length=5500, null=True, upload_to='abouts_files/'),
        ),
        migrations.AddField(
            model_name='about',
            name='img_url_raised_about',
            field=models.ImageField(blank=True, max_length=5500, null=True, upload_to='about_raised_images/'),
        ),
    ]
