# Generated by Django 5.1.4 on 2025-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0014_about_file_about_about_img_url_raised_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_images_the_about_image', models.CharField(max_length=500)),
                ('img_url_about_images', models.ImageField(blank=True, max_length=5500, null=True, upload_to='about_images_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
