# Generated by Django 5.1.4 on 2025-01-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0015_aboutimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Título para la donación (ej: 'Ayuda para el Orfanato')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción breve de la donación.')),
                ('amount_required', models.DecimalField(decimal_places=2, help_text='Monto total requerido para esta donación.', max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, help_text='Monto que ya ha sido recaudado.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó la donación.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó esta donación.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si esta donación está activa y visible.')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(blank=True, help_text='Título del post', max_length=200, null=True)),
                ('description_post', models.TextField(blank=True, help_text='Descripción del post.', null=True)),
                ('link_post', models.URLField(blank=True, help_text='Enlace al post completo', max_length=4500, null=True)),
                ('explore_link_latest_post_date_footer', models.DateField(blank=True, help_text='Fecha de publicación', null=True)),
                ('explore_link_latest_post_time_footer', models.TimeField(blank=True, help_text='Hora de publicación', null=True)),
                ('explore_link_latest_post_day_footer', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Dia de publicación', max_length=9)),
                ('image_post', models.ImageField(blank=True, help_text='Imagen del post', max_length=5500, null=True, upload_to='latest_posts/')),
                ('file_post', models.FileField(blank=True, help_text='File del post', max_length=5500, null=True, upload_to='posts_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_footer', models.CharField(blank=True, help_text='Subscribe_footer', max_length=500, null=True)),
                ('description_subscribe_footer', models.TextField(blank=True, null=True)),
                ('subscibe_boton_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('themosque_footer', models.TextField(blank=True, null=True)),
                ('themosque_description_footer', models.TextField(blank=True, null=True)),
                ('our_mosque_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('our_address_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('our_address_address_footer', models.TextField(blank=True, null=True)),
                ('our_mobile_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('our_mobile_mobile_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('explore_link_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('explore_link_home_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('explore_link_latest_post_footer', models.CharField(blank=True, max_length=500, null=True)),
                ('date_footer', models.DateField(blank=True, help_text='Fecha de footer', null=True)),
                ('time_footer', models.TimeField(blank=True, help_text='Hora de footer', null=True)),
                ('day_footer', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('description_footer', models.TextField()),
                ('title_footer', models.CharField(blank=True, help_text='Título del Footer', max_length=500, null=True)),
                ('link_footer', models.URLField(blank=True, max_length=4500, null=True)),
                ('img_url_footer', models.ImageField(blank=True, max_length=5500, null=True, upload_to='footer_images/')),
                ('file_footer', models.FileField(blank=True, max_length=5500, null=True, upload_to='footer_files/')),
                ('site_name_footer', models.CharField(blank=True, help_text='Site name', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el footer.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el footer.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este footer está activa y visible.')),
                ('explore_link_about_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.about')),
                ('explore_link_blog_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.blog')),
                ('explore_link_contact_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.contactmessage')),
                ('explore_link_donations_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.donation')),
                ('explore_link_events_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.event')),
                ('explore_link_features_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.activity')),
                ('explore_link_sermons_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.sermon')),
                ('explore_link_posts_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.post')),
            ],
        ),
    ]
