# Generated by Django 5.1.4 on 2025-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0016_donation_post_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_collected',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto que ya ha sido recaudado.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total requerido para esta donación.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción breve de la donación.', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='title',
            field=models.CharField(blank=True, help_text="Título para la donación (ej: 'Ayuda para el Orfanato')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si este footer está activo y visible.'),
        ),
    ]
