# Generated by Django 5.1.4 on 2025-01-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0018_contactinfo_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_video_ref', models.CharField(max_length=500)),
                ('best_video_name', models.CharField(max_length=1000)),
                ('best_video_description', models.TextField()),
                ('best_video_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='best_video_img_url_images/')),
                ('best_video_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='best_video_file_files/')),
                ('date_page', models.DateField(blank=True, help_text='Fecha de BestVideos', null=True)),
                ('time_page', models.TimeField(blank=True, help_text='Hora de BestVideos', null=True)),
                ('day_page', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el BestVideos.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el BestVideos.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este BestVideos está activo y visible.')),
            ],
        ),
    ]
