# Generated by Django 5.1.4 on 2025-01-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0019_bestvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestvideos',
            name='best_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Best videos URL'),
        ),
    ]
