# Generated by Django 5.1.4 on 2025-02-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0021_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='tab_date_page',
            field=models.DateField(blank=True, help_text='Fecha de tab', null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='tab_time_page',
            field=models.TimeField(blank=True, help_text='Hora de tab', null=True),
        ),
        migrations.CreateModel(
            name='TabPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_page_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='tab page name')),
                ('tab_page_url_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='tab page URL name')),
                ('tab_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='tab_page_img_url_images/')),
                ('tab_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='tab_page_file_files/')),
                ('tab_date_page', models.DateField(blank=True, help_text='Fecha de tab page', null=True)),
                ('tab_time_page', models.TimeField(blank=True, help_text='Hora de tab page', null=True)),
                ('tab_day_page', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el tab page.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab page.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este tab page está activo y visible.')),
                ('tab_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosque_web_app.tab')),
            ],
        ),
    ]
