# Generated by Django 5.1.4 on 2025-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0022_alter_tab_tab_date_page_alter_tab_tab_time_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_more_slug', models.SlugField(help_text='Identificador único de la pestaña (ej: home, about, event)', unique=True)),
                ('read_more_nombre', models.CharField(max_length=100)),
                ('read_more_description', models.TextField()),
                ('read_more_url', models.URLField(blank=True, null=True, verbose_name='Read More URL')),
                ('read_more_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='read_more_img_url_images/')),
                ('read_more_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='read_more_file_files/')),
                ('read_more_date_page', models.DateField(blank=True, help_text='Fecha de read more', null=True)),
                ('read_more_time_page', models.TimeField(blank=True, help_text='Hora de read more', null=True)),
                ('read_more_day_page', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el read more.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el read more.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este read more está activo y visible.')),
            ],
        ),
    ]
