# Generated by Django 5.1.4 on 2025-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque_web_app', '0026_moredetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_now_slug', models.SlugField(help_text='Identificador único de la sección (ej: home, about, event)', unique=True)),
                ('donate_now_nombre', models.CharField(max_length=100)),
                ('donate_now_description', models.TextField()),
                ('donate_now_url', models.URLField(blank=True, null=True, verbose_name='Donate Now URL')),
                ('donate_now_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='donate_now_img_url_images/')),
                ('donate_now_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='donate_now_file_files/')),
                ('donate_now_date_page', models.DateField(blank=True, help_text='Fecha de Donate Now', null=True)),
                ('donate_now_time_page', models.TimeField(blank=True, help_text='Hora de Donate Now', null=True)),
                ('donate_now_day_page', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el Donate Now.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el Donate Now.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este Donate Now está activo y visible.')),
            ],
        ),
    ]
